export const CONNECT_METAMASK = 'CONNECT_METAMASK'
export const CONNECT_METAMASK_PASSIVE = 'CONNECT_METAMASK_PASSIVE'
export const METAMASK_CONNECTED = 'METAMASK_CONNECTED'

export const GET_BALANCES = 'GET_BALANCES'
export const BALANCES_RETURNED = 'BALANCES_RETURNED'

export const GET_PRICES = 'GET_PRICES'
export const PRICES_RETURNED = 'PRICES_RETURNED'

export const GET_INVESTED_BALANCES = 'GET_INVESTED_BALANCES'
export const INVESTED_BALANCES_RETURNED = 'INVESTED_BALANCES_RETURNED'

export const GET_POOL_VALUES = 'GET_POOL_VALUES'
export const POOL_VALUES_RETURNED = 'POOL_VALUES_RETURNED'

export const INVEST = 'INVEST'
export const INVEST_RETURNED = 'INVEST_RETURNED'

export const REDEEM = 'REDEEM'
export const REDEEM_RETURNED = 'REDEEM_RETURNED'

export const ERROR = 'ERROR'

export const GET_ETH_BALANCE = 'GET_ETH_BALANCE'
export const ETH_BALANCE_RETURNED = 'ETH_BALANCE_RETURNED'

export const GET_IETH_BALANCE = 'GET_IETH_BALANCE'
export const IETH_BALANCE_RETURNED = 'IETH_BALANCE_RETURNED'
